// ==========================
// CICLO PIxTI
// ==========================
const fases = document.querySelectorAll(".fase");
const descripcion = document.getElementById("ciclo-descripcion");

let index = 0;

function activarFase(i) {
  fases.forEach(f => f.classList.remove("activa"));

  fases[i].classList.add("activa");
  descripcion.textContent = fases[i].getAttribute("data-text");
}

// animación automática
setInterval(() => {
  activarFase(index);
  index = (index + 1) % fases.length;
}, 2000);

// interacción manual
fases.forEach((fase, i) => {
  fase.addEventListener("click", () => {
    index = i;
    activarFase(index);
  });
});

// ==========================
// TRADUCCIONES
// ==========================
const translations = {
  es: {
    // HERO
    hero_title: "Entrenamiento desde adentro hacia afuera",
    hero_desc: "Un modelo de entrenamiento basado en la generación y control de resistencia interna mediante oposición neuromuscular.",
    hero_phrase: "La carga se construye desde el propio cuerpo.",

    // MENÚ
    menu_method: "Método",
    menu_cycle: "Ciclo",
    menu_concepts: "Conceptos",
    menu_science: "Ciencia",
    menu_author: "Autor",

    // CICLO
    fase1: "Activación isométrica",
    fase1_desc: "Generación de tensión contra una referencia estable",

    fase2: "Tensión interna",
    fase2_desc: "Acumulación de energía interna sin desplazamiento visible",

    fase3: "Oposición",
    fase3_desc: "Resistencia generada por el propio sistema neuromuscular",

    fase4: "Modulación",
    fase4_desc: "Regulación consciente del esfuerzo durante el movimiento",

    fase5: "Movimiento",
    fase5_desc: "Movimiento generado dentro de un entorno de tensión constante"

    // MÉTODO
metodo_title: "¿Qué es PIxTI?",
metodo_p1: "PIxTI (Principios Isométricos para la Transformación Isotónica) es un sistema de entrenamiento neuromuscular basado en la generación consciente de tensión interna.",
metodo_p2: "El método integra activación muscular, control neuromuscular y oposición interna para producir movimiento bajo condiciones de tensión continua.",
metodo_l1: "Se genera tensión",
metodo_l2: "Se sostiene esa tensión",
metodo_l3: "Se produce movimiento dentro de esa tensión",

// CONCEPTOS
concepts_title: "Conceptos clave",

fixed_point_title: "Punto fijo",
fixed_point_desc: "El punto fijo organiza la dirección de la tensión.",

internal_load_title: "Pesa interna",
internal_load_desc: "El cuerpo genera su propia resistencia.",

cocontraction_title: "Co-contracción",
cocontraction_desc: "La resistencia se organiza a nivel del sistema."
  },

  en: {
    // HERO
    hero_title: "Training from the inside out",
    hero_desc: "A training model based on the generation and control of internal resistance through neuromuscular opposition.",
    hero_phrase: "Load is built from within the body.",

    // MENÚ
    menu_method: "Method",
    menu_cycle: "Cycle",
    menu_concepts: "Concepts",
    menu_science: "Science",
    menu_author: "Author",

    // CICLO
    fase1: "Isometric activation",
    fase1_desc: "Generation of tension against a stable reference",

    fase2: "Internal tension",
    fase2_desc: "Accumulation of internal energy without visible displacement",

    fase3: "Opposition",
    fase3_desc: "Resistance generated by the neuromuscular system itself",

    fase4: "Modulation",
    fase4_desc: "Conscious regulation of effort during movement",

    fase5: "Movement",
    fase5_desc: "Movement generated within a constant tension environment"

    // MÉTODO
metodo_title: "What is PIxTI?",
metodo_p1: "PIxTI (Isometric Principles for Isotonic Transformation) is a neuromuscular training system based on the conscious generation of internal tension.",
metodo_p2: "The method integrates muscle activation, neuromuscular control, and internal opposition to produce movement under continuous tension conditions.",
metodo_l1: "Tension is generated",
metodo_l2: "That tension is sustained",
metodo_l3: "Movement is produced within that tension",

// CONCEPTOS
concepts_title: "Key concepts",

fixed_point_title: "Fixed point",
fixed_point_desc: "The fixed point organizes the direction of tension.",

internal_load_title: "Internal load",
internal_load_desc: "The body generates its own resistance.",

cocontraction_title: "Co-contraction",
cocontraction_desc: "Resistance is organized at the system level."
  }
};

// ==========================
// CAMBIO DE IDIOMA
// ==========================
function setLang(lang) {
  // guardar idioma
  localStorage.setItem("lang", lang);

  const elements = document.querySelectorAll("[data-key]");
  
  elements.forEach(el => {
    const key = el.getAttribute("data-key");

    // texto visible
    if (translations[lang][key]) {
      el.textContent = translations[lang][key];
    }

    // descripciones del ciclo
    if (el.dataset.textKey && translations[lang][el.dataset.textKey]) {
      el.setAttribute("data-text", translations[lang][el.dataset.textKey]);
    }
  });

  // actualizar descripción activa del ciclo
  if (fases[index]) {
    descripcion.textContent = fases[index].getAttribute("data-text");
  }
}
// idioma inicial
const savedLang = localStorage.getItem("lang") || "es";
setLang(savedLang);
